<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>NU1902;CS9113</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ContractIQ.Workflow.Domain\ContractIQ.Workflow.Domain.csproj" />
    <ProjectReference Include="..\..\SharedKernel\ContractIQ.SharedKernel\ContractIQ.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.2.0" />
  </ItemGroup>
</Project>
