<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>NU1902;CS9113</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\ContractIQ.SharedKernel\ContractIQ.SharedKernel.csproj" />
    <ProjectReference Include="..\ContractIQ.Contracts.Domain\ContractIQ.Contracts.Domain.csproj" />
    <ProjectReference Include="..\ContractIQ.Contracts.Application\ContractIQ.Contracts.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
  </ItemGroup>
</Project>
